version: '3'

services:
  backend:
    build:
      context: ./backend
    command: gunicorn core.wsgi --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
  frontend:
    build:
      context: ./frontend/client
    ports:
      - "3000:3000"
    depends_on:
      - backend
  middleware:
    build:
        context: ./frontend/
    ports:
      - "5000:5000"
  nginx:
    depends_on:
      - backend
      - frontend
      - middleware
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - 80:80


