# Generated by Django 3.2.16 on 2023-02-13 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCarrera', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaInicio', models.DateField()),
                ('fechaTermino', models.DateField()),
                ('nroFolio', models.IntegerField()),
                ('rutAlumno', models.CharField(max_length=100)),
                ('motivo', models.TextField()),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitudes.carrera')),
            ],
        ),
    ]
