# Generated by Django 3.2.16 on 2023-02-22 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='nroFolio',
            field=models.IntegerField(null=True),
        ),
    ]
