# Generated by Django 3.2.16 on 2023-02-22 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0002_alter_solicitud_nrofolio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='nroFolio',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
