# Generated by Django 3.2.16 on 2023-02-22 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0003_alter_solicitud_nrofolio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ramos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asignatura1Nombre', models.CharField(max_length=255)),
                ('asignatura1NRC', models.CharField(max_length=255)),
                ('asignatura1NombreDoc', models.CharField(max_length=255)),
                ('asignatura1CorreoDoc', models.EmailField(max_length=254)),
                ('asignatura2Nombre', models.CharField(max_length=255)),
                ('asignatura2NRC', models.CharField(max_length=20)),
                ('asignatura2NombreDoc', models.CharField(max_length=255)),
                ('asignatura2CorreoDoc', models.EmailField(max_length=254)),
                ('asignatura3Nombre', models.CharField(max_length=20)),
                ('asignatura3NRC', models.CharField(max_length=20)),
                ('asignatura3NombreDoc', models.CharField(max_length=20)),
                ('asignatura3CorreoDoc', models.EmailField(max_length=20)),
                ('asignatura4Nombre', models.CharField(max_length=20)),
                ('asignatura4NRC', models.CharField(max_length=20)),
                ('asignatura4NombreDoc', models.CharField(max_length=20)),
                ('asignatura4CorreoDoc', models.EmailField(max_length=20)),
                ('asignatura5Nombre', models.CharField(max_length=20)),
                ('asignatura5NRC', models.CharField(max_length=20)),
                ('asignatura5NombreDoc', models.CharField(max_length=20)),
                ('asignatura5CorreoDoc', models.EmailField(max_length=20)),
                ('asignatura6Nombre', models.CharField(max_length=20)),
                ('asignatura6NRC', models.CharField(max_length=20)),
                ('asignatura6NombreDoc', models.CharField(max_length=20)),
                ('asignatura6CorreoDoc', models.EmailField(max_length=20)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitudes.solicitud')),
            ],
        ),
    ]
