# Generated by Django 3.2.16 on 2023-02-22 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0004_ramos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ramos',
            name='asignatura2CorreoDoc',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='ramos',
            name='asignatura2NRC',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ramos',
            name='asignatura2Nombre',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ramos',
            name='asignatura2NombreDoc',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ramos',
            name='asignatura3CorreoDoc',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='ramos',
            name='asignatura3NRC',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ramos',
            name='asignatura3Nombre',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ramos',
            name='asignatura3NombreDoc',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ramos',
            name='asignatura4CorreoDoc',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='ramos',
            name='asignatura4NRC',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ramos',
            name='asignatura4Nombre',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ramos',
            name='asignatura4NombreDoc',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ramos',
            name='asignatura5CorreoDoc',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='ramos',
            name='asignatura5NRC',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ramos',
            name='asignatura5Nombre',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ramos',
            name='asignatura5NombreDoc',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ramos',
            name='asignatura6CorreoDoc',
            field=models.EmailField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ramos',
            name='asignatura6NRC',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ramos',
            name='asignatura6Nombre',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ramos',
            name='asignatura6NombreDoc',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
