# Generated by Django 3.2.16 on 2023-02-23 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0005_auto_20230222_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='archivo',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
