# Generated by Django 3.2.16 on 2023-02-24 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0006_solicitud_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='estado',
            field=models.IntegerField(default=0),
        ),
    ]
