# Generated by Django 3.2.16 on 2023-02-25 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0007_solicitud_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='cantRamos',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
