# Generated by Django 3.2.16 on 2023-03-01 00:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0009_alter_solicitud_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='nombreAlumno',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
