# Generated by Django 3.2.16 on 2023-03-01 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0010_solicitud_nombrealumno'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='correoAlumno',
            field=models.EmailField(default='corre@gmail.com', max_length=100),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='telefono',
            field=models.CharField(default='+56911111111', max_length=100),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='nombreAlumno',
            field=models.CharField(default='Nombre', max_length=100),
        ),
    ]
