# Generated by Django 3.2.16 on 2023-03-02 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0011_auto_20230301_0209'),
    ]

    operations = [
        migrations.AddField(
            model_name='ramos',
            name='asignatura1Codigo',
            field=models.CharField(default='DAM-11111', max_length=255),
        ),
        migrations.AddField(
            model_name='ramos',
            name='asignatura2Codigo',
            field=models.CharField(default='DAM-11111', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ramos',
            name='asignatura3Codigo',
            field=models.CharField(default='DAM-11111', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ramos',
            name='asignatura4Codigo',
            field=models.CharField(default='DAM-11111', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ramos',
            name='asignatura5Codigo',
            field=models.CharField(default='DAM-11111', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ramos',
            name='asignatura6Codigo',
            field=models.CharField(default='DAM-11111', max_length=255, null=True),
        ),
    ]
