# Generated by Django 3.2.16 on 2023-03-03 16:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0012_auto_20230302_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
