# Generated by Django 3.2.16 on 2023-03-06 14:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0013_solicitud_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='archivo',
            field=models.FileField(null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xml'])]),
        ),
    ]
