# Generated by Django 3.2.16 on 2023-02-13 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='carrera',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='solicitudes.carrera'),
        ),
    ]
